## Pytorch tensors and numpy

Numpy Is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()



In [3]:
import torch
import numpy as np

In [5]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch tensor will be float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [7]:
# Changing tensor to Numpy array which will default to float32
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Numpy arrays and Tensors don't share memory.
  

Reproduceability (trying to take random out of random)

In short how a neural network learns:

`start with random numbers > tensor operations - update random numbers to try and
make them better representations of the data → again → again -> again…`

To reduce the randomness in neural networks and PyTorch comes the concept of a ***random seed***

Essentially what the random seed does is "flavors" the randomness

In [10]:
random_tensorA = torch.rand(3, 4)
random_tensorB = torch.rand(3, 4)
print(f"random_tensorA: {random_tensorA}")
print(f"random_tensorB: {random_tensorB}")
print(random_tensorA == random_tensorB)

random_tensorA: tensor([[0.9584, 0.9425, 0.5429, 0.5598],
        [0.5752, 0.5987, 0.2505, 0.1015],
        [0.5574, 0.8892, 0.2488, 0.7532]])
random_tensorB: tensor([[0.5203, 0.6183, 0.2412, 0.0882],
        [0.9430, 0.0077, 0.1268, 0.6401],
        [0.7976, 0.4162, 0.0629, 0.9820]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
# Let's make some random but reproducible tensor
# This will keep the randomness enclosed to just the RANDOM_SEED
# Basically keeping the random numbers the same all the time.
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3, 4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
