In [1]:
import torch

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all one dimensions from a tensor
* Unsqueeze - add a one dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swappped) in a certain way.


In [2]:
# Let create a tensor largest number in arange is not included
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
# Add an extra dimension when reshaping the new shape has to match the old shape
# When reshaping the reshape parameters must be a multiple of the largest number in the tensor
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [4]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
# Changing z changes x  (Because a view of a tensor shares the same memory as the original input.)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [6]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
# Squeezing the tensor torch.squeeze - Remove all single dimensions from a target tensor
# Or removes all the ones os [1, 9] will be just 9. [1, 1, 9] will be just [9]
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [8]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim or dimension or column in 
# a tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [10]:
# torch.premute - Rearranges The dimensions of a target tensor in a specified order
# or swapping the order of the dimension or columns

x_original = torch.rand(size=(224, 224, 3)) # [average, image size, height, width, color_channels]

# Premute the original tensor to rearrange the axis (or dim or column) order
x_premuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"Premuted output: {x_premuted}")
print(f"New shape: {x_premuted.shape}")



Previous shape: torch.Size([224, 224, 3])
Premuted output: tensor([[[0.4374, 0.7985, 0.1347,  ..., 0.4386, 0.1698, 0.5891],
         [0.5930, 0.4821, 0.0306,  ..., 0.3946, 0.3034, 0.2519],
         [0.4291, 0.8343, 0.9097,  ..., 0.9328, 0.4258, 0.8844],
         ...,
         [0.2627, 0.4763, 0.7695,  ..., 0.1963, 0.3756, 0.5866],
         [0.3149, 0.5013, 0.0763,  ..., 0.3326, 0.3931, 0.9442],
         [0.9288, 0.5280, 0.6879,  ..., 0.9052, 0.9028, 0.8973]],

        [[0.9976, 0.8579, 0.9320,  ..., 0.2382, 0.9490, 0.2680],
         [0.2225, 0.2155, 0.3238,  ..., 0.6643, 0.5637, 0.7665],
         [0.9463, 0.7468, 0.7546,  ..., 0.4349, 0.4718, 0.8391],
         ...,
         [0.3692, 0.9900, 0.0523,  ..., 0.8638, 0.6130, 0.0765],
         [0.6828, 0.6522, 0.4940,  ..., 0.3208, 0.4885, 0.8102],
         [0.9781, 0.2101, 0.5984,  ..., 0.7789, 0.0451, 0.5061]],

        [[0.3578, 0.7713, 0.9671,  ..., 0.5649, 0.4842, 0.8248],
         [0.8281, 0.3059, 0.0791,  ..., 0.0904, 0.3768, 0.8679],

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing wih NumPy.

In [11]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [12]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
# Let me get the first row the the tensor.
x[0][0]

tensor([1, 2, 3])

In [14]:
# Let me get the last row of the tensor.
x[0][2]

tensor([7, 8, 9])

In [15]:
x[0][0][0]

tensor(1)

In [16]:
x[0][2][2]

tensor(9)

In [17]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
x[0][1][2]

tensor(6)

In [38]:
# Get all the values of the 0th and 1st Dimensions, but only the index 1 of 2nd dimension.
x[:, :, 1]

tensor([[2, 5, 8]])

In [39]:
# Get all the values of the 0 dimension, but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [42]:
# Get index 0 of 0th dimension and 1st dimension and all the values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [54]:
# Index on x to return 9 as an exercise
x[0, 2, 2:]

tensor([9])

In [61]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])